CREATE DATABASE IF NOT EXISTS comunidades_db;
USE comunidades_db;

CREATE TABLE comunidades (
    parent_code INT,
    label VARCHAR(100),
    code INT PRIMARY KEY
);

CREATE TABLE provincias (
    parent_code INT,
    code INT PRIMARY KEY,
    label VARCHAR(100),
    FOREIGN KEY (parent_code) REFERENCES comunidades(code)
);

CREATE TABLE poblaciones (
    town_code INT AUTO_INCREMENT PRIMARY KEY,
    parent_code INT,
    label VARCHAR(100),
    FOREIGN KEY (parent_code) REFERENCES provincias(code)
);

INSERT INTO comunidades (parent_code, label, code) VALUES
(0, 'Comunitat Valenciana', 10);

INSERT INTO provincias (parent_code, code, label) VALUES
(10, 3, 'Alicante/Alacant'),
(10, 12, 'Castellón/Castelló'),
(11, 46, 'Valencia/València');

INSERT INTO poblaciones (parent_code, label) VALUES
(3, 'Agost'),
(3, 'Agres'),
(3, 'Aigües'),
(3, 'Albatera'),
(3, 'Alcalalí'),
(3, 'Alcocer de Planes'),
(3, 'Alcoleja'),
(3, 'Alcoy/Alcoi'),
(3, 'Alfafara'),
(3, 'Alfàs del Pi, l'''),
(3, 'Algorfa'),
(3, 'Algueña'),
(3, 'Alicante/Alacant'),
(3, 'Almoradí'),
(3, 'Almudaina'),
(3, 'Alqueria d''Asnar, l'''),
(3, 'Altea'),
(3, 'Aspe'),
(3, 'Atzúbia, l'''),
(3, 'Balones'),
(3, 'Banyeres de Mariola'),
(3, 'Benasau'),
(3, 'Beneixama'),
(3, 'Benejúzar'),
(3, 'Benferri'),
(3, 'Beniarbeig'),
(3, 'Beniardá'),
(3, 'Beniarrés'),
(3, 'Benidoleig'),
(3, 'Benidorm'),
(3, 'Benifallim'),
(3, 'Benifato'),
(3, 'Benigembla'),
(3, 'Benijófar'),
(3, 'Benilloba'),
(3, 'Benillup'),
(3, 'Benimantell'),
(3, 'Benimarfull'),
(3, 'Benimassot'),
(3, 'Benimeli'),
(3, 'Benissa'),
(3, 'Benitachell/Poble Nou de Benitatxell, el'),
(3, 'Biar'),
(3, 'Bigastro'),
(3, 'Bolulla'),
(3, 'Busot'),
(3, 'Callosa de Segura'),
(3, 'Callosa d''en Sarrià'),
(3, 'Calp'),
(3, 'Campello, el'),
(3, 'Campo de Mirra/Camp de Mirra, el'),
(3, 'Cañada'),
(3, 'Castalla'),
(3, 'Castell de Castells'),
(3, 'Castell de Guadalest, el'),
(3, 'Catral'),
(3, 'Cocentaina'),
(3, 'Confrides'),
(3, 'Cox'),
(3, 'Crevillent'),
(3, 'Daya Nueva'),
(3, 'Daya Vieja'),
(3, 'Dénia'),
(3, 'Dolores'),
(3, 'Elche/Elx'),
(3, 'Elda'),
(3, 'Facheca'),
(3, 'Famorca'),
(3, 'Finestrat'),
(3, 'Fondó de les Neus, el/Hondón de las Nieves'),
(3, 'Formentera del Segura'),
(3, 'Gaianes'),
(3, 'Gata de Gorgos'),
(3, 'Gorga'),
(3, 'Granja de Rocamora'),
(3, 'Guardamar del Segura'),
(3, 'Hondón de los Frailes'),
(3, 'Ibi'),
(3, 'Jacarilla'),
(3, 'Jávea/Xàbia'),
(3, 'Jijona/Xixona'),
(3, 'Llíber'),
(3, 'Lorcha/Orxa, l'''),
(3, 'Millena'),
(3, 'Monforte del Cid'),
(3, 'Monóvar/Monòver'),
(3, 'Montesinos, Los'),
(3, 'Murla'),
(3, 'Muro de Alcoy'),
(3, 'Mutxamel'),
(3, 'Novelda'),
(3, 'Nucia, la'),
(3, 'Ondara'),
(3, 'Onil'),
(3, 'Orba'),
(3, 'Orihuela'),
(3, 'Orxeta'),
(3, 'Parcent'),
(3, 'Pedreguer'),
(3, 'Pego'),
(3, 'Penàguila'),
(3, 'Petrer'),
(3, 'Pilar de la Horadada'),
(3, 'Pinós, el/Pinoso'),
(3, 'Planes'),
(3, 'Poblets, els'),
(3, 'Polop'),
(3, 'Quatretondeta'),
(3, 'Rafal'),
(3, 'Ràfol d''Almúnia, el'),
(3, 'Redován'),
(3, 'Relleu'),
(3, 'Rojales'),
(3, 'Romana, la'),
(3, 'Sagra'),
(3, 'Salinas'),
(3, 'San Fulgencio'),
(3, 'San Isidro'),
(3, 'San Miguel de Salinas'),
(3, 'San Vicente del Raspeig/Sant Vicent del Raspeig'),
(3, 'Sanet y Negrals'),
(3, 'Sant Joan d''Alacant'),
(3, 'Santa Pola'),
(3, 'Sax'),
(3, 'Sella'),
(3, 'Senija'),
(3, 'Tàrbena'),
(3, 'Teulada'),
(3, 'Tibi'),
(3, 'Tollos'),
(3, 'Tormos'),
(3, 'Torremanzanas/Torre de les Maçanes, la'),
(3, 'Torrevieja'),
(3, 'Vall d''Alcalà, la'),
(3, 'Vall de Gallinera'),
(3, 'Vall de Laguar, la'),
(3, 'Vall d''Ebo, la'),
(3, 'Verger, el'),
(3, 'Villajoyosa/Vila Joiosa, la'),
(3, 'Villena'),
(3, 'Xaló'),
(12, 'Aín'),
(12, 'Albocàsser'),
(12, 'Alcalà de Xivert'),
(12, 'Alcora, l'''),
(12, 'Alcudia de Veo'),
(12, 'Alfondeguilla'),
(12, 'Algimia de Almonacid'),
(12, 'Almassora'),
(12, 'Almedíjar'),
(12, 'Almenara'),
(12, 'Alqueries, les/Alquerías del Niño Perdido'),
(12, 'Altura'),
(12, 'Arañuel'),
(12, 'Ares del Maestrat'),
(12, 'Argelita'),
(12, 'Artana'),
(12, 'Atzeneta del Maestrat'),
(12, 'Ayódar'),
(12, 'Azuébar'),
(12, 'Barracas'),
(12, 'Bejís'),
(12, 'Benafer'),
(12, 'Benafigos'),
(12, 'Benassal'),
(12, 'Benicarló'),
(12, 'Benicasim/Benicàssim'),
(12, 'Benlloc'),
(12, 'Betxí'),
(12, 'Borriana/Burriana'),
(12, 'Borriol'),
(12, 'Cabanes'),
(12, 'Càlig'),
(12, 'Canet lo Roig'),
(12, 'Castell de Cabres'),
(12, 'Castellfort'),
(12, 'Castellnovo'),
(12, 'Castellón de la Plana/Castelló de la Plana'),
(12, 'Castillo de Villamalefa'),
(12, 'Catí'),
(12, 'Caudiel'),
(12, 'Cervera del Maestre'),
(12, 'Chilches/Xilxes'),
(12, 'Chodos/Xodos'),
(12, 'Chóvar'),
(12, 'Cinctorres'),
(12, 'Cirat'),
(12, 'Cortes de Arenoso'),
(12, 'Costur'),
(12, 'Coves de Vinromà, les'),
(12, 'Culla'),
(12, 'Eslida'),
(12, 'Espadilla'),
(12, 'Fanzara'),
(12, 'Figueroles'),
(12, 'Forcall'),
(12, 'Fuente la Reina'),
(12, 'Fuentes de Ayódar'),
(12, 'Gaibiel'),
(12, 'Geldo'),
(12, 'Herbés'),
(12, 'Higueras'),
(12, 'Jana, la'),
(12, 'Jérica'),
(12, 'Llosa, la'),
(12, 'Llucena/Lucena del Cid'),
(12, 'Ludiente'),
(12, 'Mata de Morella, la'),
(12, 'Matet'),
(12, 'Moncofa'),
(12, 'Montán'),
(12, 'Montanejos'),
(12, 'Morella'),
(12, 'Navajas'),
(12, 'Nules'),
(12, 'Olocau del Rey'),
(12, 'Onda'),
(12, 'Oropesa del Mar/Orpesa'),
(12, 'Palanques'),
(12, 'Pavías'),
(12, 'Peníscola/Peñíscola'),
(12, 'Pina de Montalgrao'),
(12, 'Pobla de Benifassà, la'),
(12, 'Pobla Tornesa, la'),
(12, 'Portell de Morella'),
(12, 'Puebla de Arenoso'),
(12, 'Ribesalbes'),
(12, 'Rossell'),
(12, 'Sacañet'),
(12, 'Salzadella, la'),
(12, 'San Rafael del Río'),
(12, 'Sant Joan de Moró'),
(12, 'Sant Jordi/San Jorge'),
(12, 'Sant Mateu'),
(12, 'Santa Magdalena de Pulpis'),
(12, 'Segorbe'),
(12, 'Serratella, la'),
(12, 'Sierra Engarcerán'),
(12, 'Soneja'),
(12, 'Sot de Ferrer'),
(12, 'Sueras/Suera'),
(12, 'Tales'),
(12, 'Teresa'),
(12, 'Tírig'),
(12, 'Todolella'),
(12, 'Toga'),
(12, 'Torás'),
(12, 'Toro, El'),
(12, 'Torralba del Pinar'),
(12, 'Torre d''En Besora, la'),
(12, 'Torre d''en Doménec, la'),
(12, 'Torreblanca'),
(12, 'Torrechiva'),
(12, 'Traiguera'),
(12, 'Useras/Useres, les'),
(12, 'Vall d''Alba'),
(12, 'Vall de Almonacid'),
(12, 'Vall d''Uixó, la'),
(12, 'Vallat'),
(12, 'Vallibona'),
(12, 'Vilafamés'),
(12, 'Vilafranca/Villafranca del Cid'),
(12, 'Vilanova d''Alcolea'),
(12, 'Vilar de Canes'),
(12, 'Vila-real'),
(12, 'Vilavella, la'),
(12, 'Villahermosa del Río'),
(12, 'Villamalur'),
(12, 'Villanueva de Viver'),
(12, 'Villores'),
(12, 'Vinaròs'),
(12, 'Vistabella del Maestrat'),
(12, 'Viver'),
(12, 'Xert'),
(12, 'Zorita del Maestrazgo'),
(12, 'Zucaina'),
(46, 'Ademuz'),
(46, 'Ador'),
(46, 'Agullent'),
(46, 'Aielo de Malferit'),
(46, 'Aielo de Rugat'),
(46, 'Alaquàs'),
(46, 'Albaida'),
(46, 'Albal'),
(46, 'Albalat de la Ribera'),
(46, 'Albalat dels Sorells'),
(46, 'Albalat dels Tarongers'),
(46, 'Alberic'),
(46, 'Alborache'),
(46, 'Alboraia/Alboraya'),
(46, 'Albuixech'),
(46, 'Alcàntera de Xúquer'),
(46, 'Alcàsser'),
(46, 'Alcublas'),
(46, 'Alcúdia de Crespins, l'''),
(46, 'Alcúdia, l'''),
(46, 'Aldaia'),
(46, 'Alfafar'),
(46, 'Alfara de la Baronia'),
(46, 'Alfara del Patriarca'),
(46, 'Alfarp'),
(46, 'Alfarrasí'),
(46, 'Alfauir'),
(46, 'Algar de Palancia'),
(46, 'Algemesí'),
(46, 'Algímia d''Alfara'),
(46, 'Alginet'),
(46, 'Almàssera'),
(46, 'Almiserà'),
(46, 'Almoines'),
(46, 'Almussafes'),
(46, 'Alpuente'),
(46, 'Alqueria de la Comtessa, l'''),
(46, 'Alzira'),
(46, 'Andilla'),
(46, 'Anna'),
(46, 'Antella'),
(46, 'Aras de los Olmos'),
(46, 'Atzeneta d''Albaida'),
(46, 'Ayora'),
(46, 'Barx'),
(46, 'Barxeta'),
(46, 'Bèlgida'),
(46, 'Bellreguard'),
(46, 'Bellús'),
(46, 'Benagéber'),
(46, 'Benaguasil'),
(46, 'Benavites'),
(46, 'Beneixida'),
(46, 'Benetússer'),
(46, 'Beniarjó'),
(46, 'Beniatjar'),
(46, 'Benicolet'),
(46, 'Benicull de Xúquer'),
(46, 'Benifaió'),
(46, 'Benifairó de la Valldigna'),
(46, 'Benifairó de les Valls'),
(46, 'Beniflá'),
(46, 'Benigànim'),
(46, 'Benimodo'),
(46, 'Benimuslem'),
(46, 'Beniparrell'),
(46, 'Benirredrà'),
(46, 'Benissanó'),
(46, 'Benissoda'),
(46, 'Benissuera'),
(46, 'Bétera'),
(46, 'Bicorp'),
(46, 'Bocairent'),
(46, 'Bolbaite'),
(46, 'Bonrepòs i Mirambell'),
(46, 'Bufali'),
(46, 'Bugarra'),
(46, 'Buñol'),
(46, 'Burjassot'),
(46, 'Calles'),
(46, 'Camporrobles'),
(46, 'Canals'),
(46, 'Canet d''En Berenguer'),
(46, 'Carcaixent'),
(46, 'Càrcer'),
(46, 'Carlet'),
(46, 'Carrícola'),
(46, 'Casas Altas'),
(46, 'Casas Bajas'),
(46, 'Casinos'),
(46, 'Castelló de Rugat'),
(46, 'Castellonet de la Conquesta'),
(46, 'Castielfabib'),
(46, 'Catadau'),
(46, 'Catarroja'),
(46, 'Caudete de las Fuentes'),
(46, 'Cerdà'),
(46, 'Chella'),
(46, 'Chelva'),
(46, 'Chera'),
(46, 'Cheste'),
(46, 'Chiva'),
(46, 'Chulilla'),
(46, 'Cofrentes'),
(46, 'Corbera'),
(46, 'Cortes de Pallás'),
(46, 'Cotes'),
(46, 'Cullera'),
(46, 'Daimús'),
(46, 'Domeño'),
(46, 'Dos Aguas'),
(46, 'Eliana, l'''),
(46, 'Emperador'),
(46, 'Enguera'),
(46, 'Ènova, l'''),
(46, 'Estivella'),
(46, 'Estubeny'),
(46, 'Faura'),
(46, 'Favara'),
(46, 'Foios'),
(46, 'Font de la Figuera, la'),
(46, 'Font d''En Carròs, la'),
(46, 'Fontanars dels Alforins'),
(46, 'Fortaleny'),
(46, 'Fuenterrobles'),
(46, 'Gandia'),
(46, 'Gátova'),
(46, 'Gavarda'),
(46, 'Genovés, el'),
(46, 'Gestalgar'),
(46, 'Gilet'),
(46, 'Godella'),
(46, 'Godelleta'),
(46, 'Granja de la Costera, la'),
(46, 'Guadasséquies'),
(46, 'Guadassuar'),
(46, 'Guardamar de la Safor'),
(46, 'Higueruelas'),
(46, 'Jalance'),
(46, 'Jarafuel'),
(46, 'Llanera de Ranes'),
(46, 'Llaurí'),
(46, 'Llíria'),
(46, 'Llocnou de la Corona'),
(46, 'Llocnou de Sant Jeroni'),
(46, 'Llocnou d''En Fenollet'),
(46, 'Llombai'),
(46, 'Llosa de Ranes, la'),
(46, 'Llutxent'),
(46, 'Loriguilla'),
(46, 'Losa del Obispo'),
(46, 'Macastre'),
(46, 'Manises'),
(46, 'Manuel'),
(46, 'Marines'),
(46, 'Massalavés'),
(46, 'Massalfassar'),
(46, 'Massamagrell'),
(46, 'Massanassa'),
(46, 'Meliana'),
(46, 'Millares'),
(46, 'Miramar'),
(46, 'Mislata'),
(46, 'Mogente/Moixent'),
(46, 'Moncada'),
(46, 'Montaverner'),
(46, 'Montesa'),
(46, 'Montitxelvo/Montichelvo'),
(46, 'Montroi/Montroy'),
(46, 'Montserrat'),
(46, 'Museros'),
(46, 'Nàquera/Náquera'),
(46, 'Navarrés'),
(46, 'Novelé/Novetlè'),
(46, 'Oliva'),
(46, 'Olleria, l'''),
(46, 'Olocau'),
(46, 'Ontinyent'),
(46, 'Otos'),
(46, 'Paiporta'),
(46, 'Palma de Gandía'),
(46, 'Palmera'),
(46, 'Palomar, el'),
(46, 'Paterna'),
(46, 'Pedralba'),
(46, 'Petrés'),
(46, 'Picanya'),
(46, 'Picassent'),
(46, 'Piles'),
(46, 'Pinet'),
(46, 'Pobla de Farnals, la'),
(46, 'Pobla de Vallbona, la'),
(46, 'Pobla del Duc, la'),
(46, 'Pobla Llarga, la'),
(46, 'Polinyà de Xúquer'),
(46, 'Potries'),
(46, 'Puçol'),
(46, 'Puebla de San Miguel'),
(46, 'Puig de Santa Maria, el'),
(46, 'Quart de les Valls'),
(46, 'Quart de Poblet'),
(46, 'Quartell'),
(46, 'Quatretonda'),
(46, 'Quesa'),
(46, 'Rafelbunyol'),
(46, 'Rafelcofer'),
(46, 'Rafelguaraf'),
(46, 'Ráfol de Salem'),
(46, 'Real'),
(46, 'Real de Gandia, el'),
(46, 'Requena'),
(46, 'Riba-roja de Túria'),
(46, 'Riola'),
(46, 'Rocafort'),
(46, 'Rotglà i Corberà'),
(46, 'Rótova'),
(46, 'Rugat'),
(46, 'Sagunto/Sagunt'),
(46, 'Salem'),
(46, 'San Antonio de Benagéber'),
(46, 'Sant Joanet'),
(46, 'Sedaví'),
(46, 'Segart'),
(46, 'Sellent'),
(46, 'Sempere'),
(46, 'Senyera'),
(46, 'Serra'),
(46, 'Siete Aguas'),
(46, 'Silla'),
(46, 'Simat de la Valldigna'),
(46, 'Sinarcas'),
(46, 'Sollana'),
(46, 'Sot de Chera'),
(46, 'Sueca'),
(46, 'Sumacàrcer'),
(46, 'Tavernes Blanques'),
(46, 'Tavernes de la Valldigna'),
(46, 'Teresa de Cofrentes'),
(46, 'Terrateig'),
(46, 'Titaguas'),
(46, 'Torrebaja'),
(46, 'Torrella'),
(46, 'Torrent'),
(46, 'Torres Torres'),
(46, 'Tous'),
(46, 'Tuéjar'),
(46, 'Turís'),
(46, 'Utiel'),
(46, 'València'),
(46, 'Vallada'),
(46, 'Vallanca'),
(46, 'Vallés'),
(46, 'Venta del Moro'),
(46, 'Vilallonga/Villalonga'),
(46, 'Vilamarxant'),
(46, 'Villanueva de Castellón'),
(46, 'Villar del Arzobispo');